# /bin/zsh
# Set Heroku environment variables

source .env
APP_NAME=sleeper-service

echo "Setting environment variables..."

heroku config:set \
  OPENAI_API_KEY=$OPENAI_API_KEY \
  AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID \
  AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET \
  AUTH0_AUDIENCE=$AUTH0_AUDIENCE \
  AUTH0_TOKEN_URL=$AUTH0_TOKEN_URL \
  SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN \
  SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET \
  SLACK_APP_TOKEN=$SLACK_APP_TOKEN \
  SLACK_PORT=$SLACK_PORT \
  EXPRESS_PORT=$EXPRESS_PORT \
  MONGO_CONNECTION_STRING=$MONGO_CONNECTION_STRING \
  OPEN_OBSERVE_USER_ID=$OPEN_OBSERVE_USER_ID \
  OPEN_OBSERVE_API_KEY=$OPEN_OBSERVE_API_KEY \
  OPEN_OBSERVE_ORG_ID=$OPEN_OBSERVE_ORG_ID \
  OPEN_OBSERVE_STREAM_NAME=$OPEN_OBSERVE_STREAM_NAME \
  NODE_OPTIONS=$NODE_OPTIONS \
  -a $APP_NAME

heroku config -a $APP_NAME

heroku restart -a $APP_NAME